# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ocr.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 607)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(800, 607))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_paste_img = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_paste_img.setGeometry(QtCore.QRect(210, 290, 101, 41))
        self.btn_paste_img.setObjectName("btn_paste_img")
        self.btn_upload_img = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_upload_img.setGeometry(QtCore.QRect(90, 290, 91, 41))
        self.btn_upload_img.setObjectName("btn_upload_img")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(40, 340, 331, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 25, 81, 21))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(140, 20, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(140, 50, 111, 21))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 80, 111, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.btn_ocr_start = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_ocr_start.setGeometry(QtCore.QRect(130, 460, 121, 61))
        self.btn_ocr_start.setObjectName("btn_ocr_start")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 25, 371, 251))
        self.label.setTabletTracking(False)
        self.label.setAcceptDrops(True)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.result_text = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.result_text.setGeometry(QtCore.QRect(10, 25, 371, 431))
        self.result_text.setReadOnly(True)
        self.result_text.setObjectName("result_text")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(60, 480, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 480, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action1234 = QtWidgets.QAction(MainWindow)
        self.action1234.setObjectName("action1234")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menu.addAction(self.action1234)
        self.menu.addAction(self.actionHelp)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_upload_img.clicked.connect(MainWindow.upload)
        self.btn_paste_img.clicked.connect(MainWindow.paste)
        self.btn_ocr_start.clicked.connect(MainWindow.ocr)
        self.pushButton.clicked.connect(MainWindow.copy)
        self.pushButton_2.clicked.connect(MainWindow.export)
        self.action1234.triggered.connect(MainWindow.set_key)
        self.actionHelp.triggered.connect(MainWindow.help)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片文字提取工具v0.01  By jerrycoding"))
        self.groupBox_3.setTitle(_translate("MainWindow", "上传图片"))
        self.btn_paste_img.setText(_translate("MainWindow", "剪切板导入"))
        self.btn_upload_img.setText(_translate("MainWindow", "上传图片"))
        self.groupBox.setTitle(_translate("MainWindow", "识别选项"))
        self.label_3.setText(_translate("MainWindow", "图片朝向"))
        self.label_4.setText(_translate("MainWindow", "图片类型"))
        self.comboBox.setCurrentText(_translate("MainWindow", "通用文字识别"))
        self.comboBox.setItemText(0, _translate("MainWindow", "通用文字识别"))
        self.comboBox.setItemText(1, _translate("MainWindow", "通用文字高精度识别"))
        self.comboBox.setItemText(2, _translate("MainWindow", "手写文字识别"))
        self.comboBox.setItemText(3, _translate("MainWindow", "身份证识别"))
        self.comboBox.setItemText(4, _translate("MainWindow", "银行卡识别"))
        self.comboBox.setItemText(5, _translate("MainWindow", "护照识别"))
        self.comboBox.setItemText(6, _translate("MainWindow", "营业执照识别"))
        self.comboBox.setItemText(7, _translate("MainWindow", "车牌识别"))
        self.radioButton.setText(_translate("MainWindow", "正面/正页"))
        self.radioButton_2.setText(_translate("MainWindow", "反面/副业"))
        self.btn_ocr_start.setText(_translate("MainWindow", "开始识别"))
        self.groupBox_2.setTitle(_translate("MainWindow", "识别结果"))
        self.pushButton.setText(_translate("MainWindow", "复制结果"))
        self.pushButton_2.setText(_translate("MainWindow", "导出TXT文档"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action1234.setText(_translate("MainWindow", "Setting"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))


